package com.dehghanzadeh.chemtrade

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.graphics.BitmapFactory
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.Alignment
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp
import org.json.JSONArray
import org.json.JSONObject
import java.security.MessageDigest

private enum class Status { PENDING, APPROVED, REJECTED }
private enum class MarginType { PERCENT, TOMAN }
private data class Offer(val id:Int=0,val name:String="",val official:String="",val market:String="",val place:String="",val time:String="",val supplier:String="",val phone:String="",val owner:String="",val description:String="",val photo:String="",val status:Status=Status.PENDING,val reason:String="",val marginType:MarginType=MarginType.PERCENT,val margin:Double=0.0,val publishedOfficial:String="",val publishedMarket:String="")
private data class UserAccount(val phone:String,val type:String,val name:String="",val company:String="")
private val Navy=Color(0xFF0B1F33)
private val Gold=Color(0xFFC8A24A)
private val Cream=Color(0xFFFBF6EE)
private const val ADMIN_HASH="a1fb4e703a9ef1fa4936801721ff285a97ac85330856674412e054892afe6972"

private fun digits(s:String):String=s.map{c->when(c){in '۰'..'۹'->('0'.code+c.code-'۰'.code).toChar();in '٠'..'٩'->('0'.code+c.code-'٠'.code).toChar();else->c}}.joinToString("")
private fun hash(s:String):String=MessageDigest.getInstance("SHA-256").digest(s.toByteArray()).joinToString(""){ "%02x".format(it) }
private fun number(s:String):Long?=digits(s).filter(Char::isDigit).toLongOrNull()
private fun money(n:Long):String=String.format("%,d تومان",n)

private fun loadOffers(p:android.content.SharedPreferences):MutableList<Offer>{
    val arr=runCatching{JSONArray(p.getString("offers","[]")?:"[]")}.getOrDefault(JSONArray());val out=mutableListOf<Offer>()
    for(i in 0 until arr.length()){val o=arr.optJSONObject(i)?:continue;out+=Offer(o.optInt("id"),o.optString("name"),o.optString("official"),o.optString("market"),o.optString("place"),o.optString("time"),o.optString("supplier"),o.optString("phone"),o.optString("owner"),o.optString("description"),o.optString("photo"),runCatching{Status.valueOf(o.optString("status","PENDING"))}.getOrDefault(Status.PENDING),o.optString("reason"),runCatching{MarginType.valueOf(o.optString("marginType","PERCENT"))}.getOrDefault(MarginType.PERCENT),o.optDouble("margin",0.0),o.optString("publishedOfficial"),o.optString("publishedMarket"))}
    return out
}
private fun persistOffers(p:android.content.SharedPreferences,list:List<Offer>){val arr=JSONArray();list.forEach{o->arr.put(JSONObject().apply{put("id",o.id);put("name",o.name);put("official",o.official);put("market",o.market);put("place",o.place);put("time",o.time);put("supplier",o.supplier);put("phone",o.phone);put("owner",o.owner);put("description",o.description);put("photo",o.photo);put("status",o.status.name);put("reason",o.reason);put("marginType",o.marginType.name);put("margin",o.margin);put("publishedOfficial",o.publishedOfficial);put("publishedMarket",o.publishedMarket)})};p.edit().putString("offers",arr.toString()).apply()}
private fun loadUsers(p:android.content.SharedPreferences):List<UserAccount>{val arr=runCatching{JSONArray(p.getString("users","[]")?:"[]")}.getOrDefault(JSONArray());val out=mutableListOf<UserAccount>();for(i in 0 until arr.length()){val o=arr.optJSONObject(i)?:continue;out+=UserAccount(o.optString("phone"),o.optString("type"),o.optString("name"),o.optString("company"))};return out}

class MainActivity:ComponentActivity(){override fun onCreate(state:Bundle?){super.onCreate(state);setContent{ChemLinkApp()}}}
@Composable private fun ChemLinkApp(){val scheme=lightColorScheme(primary=Navy,onPrimary=Color.White,secondary=Gold,onSecondary=Navy,background=Cream,onBackground=Navy,surface=Color.White,onSurface=Navy);CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl){MaterialTheme(colorScheme=scheme){MainScreen()}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun MainScreen(){
    val ctx=LocalContext.current;val prefs=remember{ctx.getSharedPreferences("chemlink",Context.MODE_PRIVATE)}
    var admin by remember{mutableStateOf(prefs.getBoolean("adminSession",false))};var page by remember{mutableIntStateOf(0)};var adminLogin by remember{mutableStateOf(false)};var form by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<Offer?>(null)};var review by remember{mutableStateOf<Offer?>(null)};var details by remember{mutableStateOf<Offer?>(null)};var search by remember{mutableStateOf("")};var userPhone by remember{mutableStateOf(prefs.getString("phone","")?:"")};var offers by remember{mutableStateOf(loadOffers(prefs))}
    fun save(o:Offer){val list=offers.toMutableList();if(o.id==0)list+=o.copy(id=(list.maxOfOrNull{it.id}?:0)+1)else{val i=list.indexOfFirst{it.id==o.id};if(i>=0)list[i]=o else list+=o};offers=list;persistOffers(prefs,list)}
    fun logoutUser(){userPhone="";prefs.edit().remove("phone").apply();ctx.startActivity(Intent(ctx,EntryActivity::class.java));(ctx as? ComponentActivity)?.finish()}
    Scaffold(topBar={TopAppBar(title={Column{Text("ChemLink",fontWeight=FontWeight.ExtraBold);Text(if(admin)"پنل مدیریت" else "بازار مواد اولیه",style=MaterialTheme.typography.labelSmall,color=Gold)}},actions={TextButton(onClick={if(admin){admin=false;prefs.edit().putBoolean("adminSession",false).apply()}else page=3}){Text(if(admin)"خروج از مدیریت" else "تنظیمات")}})},bottomBar={if(!admin)NavigationBar{NavigationBarItem(selected=page==0,onClick={page=0},icon={Text("⌂")},label={Text("بازار")});NavigationBarItem(selected=page==1,onClick={page=1},icon={Text("+")},label={Text("ثبت آگهی")});NavigationBarItem(selected=page==2,onClick={page=2},icon={Text("●")},label={Text("حساب")});NavigationBarItem(selected=page==3,onClick={page=3},icon={Text("⚙")},label={Text("تنظیمات")})}}){pad->when{admin->AdminDashboard(Modifier.padding(pad),offers,{review=it},{save(it)},loadUsers(prefs));page==0->MarketPage(Modifier.padding(pad),offers,search,{search=it}){details=it};page==1->NewOfferPage(Modifier.padding(pad),userPhone){if(userPhone.isBlank())page=2 else{edit=null;form=true}};page==2->AccountPage(Modifier.padding(pad),userPhone,{page=0},{logoutUser()}){edit=null;form=true};else->SettingsPage(Modifier.padding(pad)){adminLogin=true}}}
    details?.let{o->OfferDetails(o){details=null}};if(adminLogin)AdminLoginDialog({adminLogin=false}){admin=true;prefs.edit().putBoolean("adminSession",true).apply();adminLogin=false};if(form)OfferFormDialog(edit,userPhone,admin,{form=false;edit=null}){o->save(o);form=false;edit=null;page=if(admin)0 else 2};review?.let{o->ReviewDialog(o,{review=null},{approved->save(approved);review=null},{target,reason->save(target.copy(status=Status.REJECTED,reason=reason));review=null})}
}

@Composable private fun MarketPage(m:Modifier,offers:List<Offer>,q:String,setQ:(String)->Unit,open:(Offer)->Unit){val list=offers.filter{it.status==Status.APPROVED&&(q.isBlank()||it.name.contains(q,true))};LazyColumn(m.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Card(colors=CardDefaults.cardColors(containerColor=Navy),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(20.dp)){Text("ChemLink",color=Color.White,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold);Text("بازار حرفه‌ای مواد اولیه",color=Gold);Text("فقط قیمت نهایی رسمی و غیررسمی نمایش داده می‌شود",color=Color.White)}};Spacer(Modifier.height(12.dp));OutlinedTextField(q,setQ,Modifier.fillMaxWidth(),singleLine=true,label={Text("جستجوی ماده")})};items(list,key={it.id}){o->Card(Modifier.fillMaxWidth().clickable{open(o)},shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(o.name,fontWeight=FontWeight.Bold);Text("قیمت نهایی رسمی: ${o.publishedOfficial}",fontWeight=FontWeight.SemiBold);Text("قیمت نهایی غیررسمی: ${o.publishedMarket}",fontWeight=FontWeight.SemiBold);Text("مکان تحویل: ${o.place}");Text("زمان تحویل: ${o.time}")}}};if(list.isEmpty())item{Text("آگهی تأییدشده‌ای وجود ندارد.")}}}

@Composable private fun AdminDashboard(m:Modifier,offers:List<Offer>,open:(Offer)->Unit,save:(Offer)->Unit,users:List<UserAccount>){var tab by remember{mutableIntStateOf(0)};var usersTab by remember{mutableStateOf(false)};val list=when(tab){0->offers.filter{it.status==Status.PENDING};1->offers.filter{it.status==Status.REJECTED};else->offers.filter{it.status==Status.APPROVED}};Column(m.padding(16.dp)){Text("مدیریت",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){Button({tab=0},Modifier.weight(1f)){Text("در انتظار ${offers.count{it.status==Status.PENDING}}")};Button({tab=1},Modifier.weight(1f)){Text("اصلاحیه ${offers.count{it.status==Status.REJECTED}}")};Button({tab=2},Modifier.weight(1f)){Text("منتشر ${offers.count{it.status==Status.APPROVED}}")}};Spacer(Modifier.height(8.dp));Button({usersTab=!usersTab},Modifier.fillMaxWidth()){Text(if(usersTab)"بازگشت به آگهی‌ها" else "تامین‌کنندگان و مصرف‌کنندگان")};if(usersTab)UserCounts(users)else LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(list,key={it.id}){o->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(o.name,fontWeight=FontWeight.Bold);Text("قیمت تامین‌کننده رسمی: ${o.official} | غیررسمی: ${o.market}");Text("تحویل: ${o.place} | ${o.time}");if(o.reason.isNotBlank())Text("اصلاحیه: ${o.reason}",color=MaterialTheme.colorScheme.error);Button({open(o)}){Text("باز کردن و بررسی کامل")}}}};if(list.isEmpty())item{Text("موردی برای نمایش نیست.")}}}}
@Composable private fun UserCounts(users:List<UserAccount>){val suppliers=users.count{it.type=="Supplier"};val consumers=users.count{it.type=="Consumer"};Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Text("ثبت‌نام کاربران",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Card(Modifier.weight(1f)){Column(Modifier.padding(16.dp)){Text("تامین‌کننده",fontWeight=FontWeight.Bold);Text("$suppliers نفر",style=MaterialTheme.typography.headlineSmall)}};Card(Modifier.weight(1f)){Column(Modifier.padding(16.dp)){Text("مصرف‌کننده",fontWeight=FontWeight.Bold);Text("$consumers نفر",style=MaterialTheme.typography.headlineSmall)}}};Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("مجموع ثبت‌نام: ${users.size} نفر",fontWeight=FontWeight.Bold);users.forEach{Text("${if(it.type=="Supplier")"تامین‌کننده" else "مصرف‌کننده"} — ${it.phone}")}}}}}

@Composable private fun ReviewDialog(o:Offer,close:()->Unit,approve:(Offer)->Unit,reject:(Offer,String)->Unit){var type by remember(o.id){mutableStateOf(o.marginType)};var value by remember(o.id){mutableStateOf(if(o.margin==0.0)"" else o.margin.toString())};var reason by remember(o.id){mutableStateOf("")};val a=number(o.official)?:0L;val b=number(o.market)?:0L;val margin=value.toDoubleOrNull()?:0.0;fun add(base:Long):Long=if(type==MarginType.PERCENT)base+(base*margin/100.0).toLong()else base+margin.toLong();val fo=add(a);val fm=add(b);AlertDialog(onDismissRequest=close,title={Text("بررسی آگهی")},text={Column(Modifier.heightIn(max=600.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(o.name,fontWeight=FontWeight.Bold);if(o.photo.isNotBlank())PhotoView(o.photo);Text("قیمت تامین‌کننده رسمی: ${o.official}");Text("قیمت تامین‌کننده غیررسمی: ${o.market}");Text("مکان تحویل: ${o.place}");Text("زمان تحویل: ${o.time}");Text("سود مدیریت روی هر دو قیمت اعمال می‌شود:");Row{FilterChip(selected=type==MarginType.PERCENT,onClick={type=MarginType.PERCENT},label={Text("درصد")});Spacer(Modifier.width(8.dp));FilterChip(selected=type==MarginType.TOMAN,onClick={type=MarginType.TOMAN},label={Text("تومان")})};OutlinedTextField(value,{value=it.filter{c->c.isDigit()||c=='.'}},Modifier.fillMaxWidth(),singleLine=true,label={Text("مقدار سود")});Text("قیمت نهایی رسمی: ${money(fo)}",fontWeight=FontWeight.Bold,color=Gold);Text("قیمت نهایی غیررسمی: ${money(fm)}",fontWeight=FontWeight.Bold,color=Gold);OutlinedTextField(reason,{reason=it},Modifier.fillMaxWidth(),label={Text("دلیل اصلاحیه")})}},confirmButton={Button({approve(o.copy(status=Status.APPROVED,marginType=type,margin=margin,publishedOfficial=money(fo),publishedMarket=money(fm)))}){Text("تأیید و انتشار")}},dismissButton={Row{TextButton(close){Text("بازگشت")};TextButton({reject(o,reason.ifBlank{"لطفاً اطلاعات آگهی اصلاح شود"})}){Text("ثبت اصلاحیه")}}})}

@Composable private fun OfferFormDialog(old:Offer?,owner:String,admin:Boolean,close:()->Unit,submit:(Offer)->Unit){var name by remember{mutableStateOf(old?.name?:"")};var official by remember{mutableStateOf(old?.official?:"")};var market by remember{mutableStateOf(old?.market?:"")};var place by remember{mutableStateOf(old?.place?:"")};var time by remember{mutableStateOf(old?.time?:"")};var supplier by remember{mutableStateOf(old?.supplier?:"")};var phone by remember{mutableStateOf(old?.phone?:owner)};var description by remember{mutableStateOf(old?.description?:"")};var photo by remember{mutableStateOf(old?.photo?:"")};val context=LocalContext.current;val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri:Uri?->uri?.let{runCatching{context.contentResolver.takePersistableUriPermission(it,Intent.FLAG_GRANT_READ_URI_PERMISSION)};photo=it.toString()}};AlertDialog(onDismissRequest=close,title={Text(if(old==null)"ثبت آگهی" else "ویرایش آگهی")},text={Column(Modifier.heightIn(max=650.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Input("نام ماده",name){name=it};Input("قیمت تامین‌کننده رسمی",official){official=it};Input("قیمت تامین‌کننده غیررسمی",market){market=it};Input("مکان تحویل",place){place=it};Input("زمان تحویل",time){time=it};Input("نام فروشنده (فقط مدیریت)",supplier){supplier=it};Input("شماره تماس",phone){phone=digits(it).filter(Char::isDigit).take(11)};Input("توضیحات",description){description=it};Button({picker.launch(arrayOf("image/*"))},Modifier.fillMaxWidth()){Text(if(photo.isBlank())"آپلود عکس محصول" else "تغییر عکس")};if(photo.isNotBlank())PhotoView(photo)}},confirmButton={Button({if(name.isNotBlank())submit(Offer(old?.id?:0,name,official,market,place,time,supplier,phone,owner,description,photo,old?.status?:if(admin)Status.APPROVED else Status.PENDING,old?.reason?:"",old?.marginType?:MarginType.PERCENT,old?.margin?:0.0,old?.publishedOfficial?:"",old?.publishedMarket?:""))}){Text("ذخیره")}},dismissButton={TextButton(close){Text("انصراف")}})}
@Composable private fun Input(label:String,value:String,onChange:(String)->Unit)=OutlinedTextField(value,onChange,Modifier.fillMaxWidth(),singleLine=true,label={Text(label)})
@Composable private fun OfferDetails(o:Offer,close:()->Unit)=AlertDialog(onDismissRequest=close,title={Text(o.name)},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){if(o.photo.isNotBlank())PhotoView(o.photo);Text("قیمت نهایی رسمی: ${o.publishedOfficial}",fontWeight=FontWeight.SemiBold);Text("قیمت نهایی غیررسمی: ${o.publishedMarket}",fontWeight=FontWeight.SemiBold);Text("تحویل: ${o.place}");Text("زمان تحویل: ${o.time}");Text("تماس: ${o.phone}");Text(o.description)}},confirmButton={TextButton(close){Text("بستن")}})
@Composable private fun PhotoView(value:String){val c=LocalContext.current;val bitmap=remember(value){runCatching{c.contentResolver.openInputStream(Uri.parse(value)).use{BitmapFactory.decodeStream(it)}}.getOrNull()};bitmap?.let{Image(it.asImageBitmap(),null,Modifier.fillMaxWidth().height(180.dp),contentScale=ContentScale.Crop)}}
@Composable private fun NewOfferPage(m:Modifier,phone:String,start:()->Unit)=Column(m.padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("ثبت آگهی مواد اولیه",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("شماره حساب: ${phone.ifBlank{"وارد نشده"}}");Spacer(Modifier.height(18.dp));Button(start,Modifier.fillMaxWidth()){Text("ایجاد آگهی")}}
@Composable private fun AccountPage(m:Modifier,phone:String,home:()->Unit,logout:()->Unit,newOffer:()->Unit)=Column(m.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("حساب کاربری",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("شماره موبایل: ${phone.ifBlank{"وارد نشده"}}");Button(newOffer,Modifier.fillMaxWidth()){Text("ثبت آگهی جدید")};OutlinedButton(home,Modifier.fillMaxWidth()){Text("بازگشت به بازار")};Button(logout,Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.error)){Text("خروج از حساب")}}
@Composable private fun SettingsPage(m:Modifier,admin:()->Unit)=Column(m.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("تنظیمات",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("مدیریت ChemLink",fontWeight=FontWeight.Bold);Text("ورود مدیریت برای بررسی آگهی‌ها، قیمت‌گذاری و آمار کاربران")}};Button(admin,Modifier.fillMaxWidth()){Text("ورود به بخش مدیریت")}}
@Composable private fun AdminLoginDialog(close:()->Unit,success:()->Unit){var code by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("ورود مدیریت")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("کد مدیریت را وارد کنید.");OutlinedTextField(code,{code=digits(it).filter(Char::isDigit).take(8)},singleLine=true,label={Text("کد مدیریت")});if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}},confirmButton={Button({if(hash(code)==ADMIN_HASH)success()else error="کد مدیریت صحیح نیست."}){Text("ورود")}},dismissButton={TextButton(close){Text("انصراف")}})}