const DB_URL='https://chemlink-8909b-default-rtdb.firebaseio.com';
const PROJECT_ID='chemlink-8909b';
const API_KEY='AIzaSyDeiURyc0INZpvA00hmRnEqwtGW3h63pgE';
let confirmationResult=null,recaptchaVerifier=null,listings=[];
const $=id=>document.getElementById(id);
const loggedIn=()=>sessionStorage.getItem('chemlinkLoggedIn')==='1';
function showLogin(){const m=$('modal');if(!m)return;m.classList.add('show','open');m.style.display='flex';m.setAttribute('aria-hidden','false');setTimeout(()=>$('phone')?.focus(),50)}
function hideLogin(){const m=$('modal');if(!m)return;m.classList.remove('show','open');m.style.display='none';m.setAttribute('aria-hidden','true')}
function showIOSInstall(){const s=$('app-download');if(!s)return;let g=$('iosInstallGuide');if(!g){g=document.createElement('div');g.id='iosInstallGuide';g.style.cssText='margin-top:18px;padding:18px 20px;border:1px solid #dbe3ee;border-radius:16px;background:#f8fafc;color:#10233e;line-height:1.9';g.innerHTML='<strong style="display:block;font-size:15px;margin-bottom:7px">📱 نصب ChemLink روی آیفون</strong><span style="display:block;font-size:12px;color:#475569">این دکمه نمی‌تواند به‌تنهایی برنامه را به صفحه اصلی آیفون اضافه کند؛ iOS این کار را از داخل Safari انجام می‌دهد.</span><ol style="margin:9px 0 0;padding-right:22px;font-size:12px;color:#334155"><li>همین سایت را با <b>Safari</b> باز کنید.</li><li>دکمه <b>Share / اشتراک‌گذاری</b> را بزنید.</li><li><b>Add to Home Screen / افزودن به صفحه اصلی</b> را انتخاب کنید.</li><li>اگر گزینه <b>Open as Web App / باز کردن به‌عنوان وب‌اپ</b> نمایش داده شد، آن را روشن کنید و <b>Add</b> را بزنید.</li></ol><div style="margin-top:10px;font-size:10px;color:#64748b">بعد از این کار آیکون ChemLink روی Home Screen آیفون اضافه می‌شود.</div>';s.querySelector('.app-download-inner')?.appendChild(g)}g.scrollIntoView({behavior:'smooth',block:'center'});g.style.boxShadow='0 0 0 3px rgba(14,165,233,.15)';setTimeout(()=>g.style.boxShadow='',1800)}
function normalizePhone(v){v=(v||'').replace(/\s|-/g,'');return v.startsWith('+98')?'0'+v.slice(3):v}
function validPhone(v){return /^09\d{9}$/.test(v)}
async function loadFirebase(){if(!window.firebase)throw new Error('Firebase SDK بارگذاری نشده است.');if(!firebase.apps.length)firebase.initializeApp({apiKey:API_KEY,authDomain:`${PROJECT_ID}.firebaseapp.com`,projectId:PROJECT_ID});if(!firebase.auth)throw new Error('Firebase Authentication SDK بارگذاری نشده است.');return firebase.auth()}
function withTimeout(p,ms,label){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(Object.assign(new Error(label),{code:'auth/timeout'})),ms))])}
async function startSmsLogin(){const phone=normalizePhone($('phone')?.value);if(!validPhone(phone)){$('modalText').textContent='شماره موبایل معتبر ۱۱ رقمی وارد کنید.';return}const button=$('modalAction');button.disabled=true;$('modalText').textContent='در حال آماده‌سازی ارسال کد...';try{const auth=await withTimeout(loadFirebase(),10000,'Firebase SDK/Authentication پاسخ نداد.');if(recaptchaVerifier){try{recaptchaVerifier.clear()}catch(_){}recaptchaVerifier=null}$('recaptcha-container').innerHTML='';recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha-container',{size:'normal',callback:()=>{$('modalText').textContent='تأیید امنیتی انجام شد؛ در حال ارسال پیامک...'},'expired-callback':()=>{$('modalText').textContent='تأیید امنیتی منقضی شد؛ دوباره تیک را بزنید.'}});$('modalText').textContent='لطفاً تیک «من ربات نیستم» را بزنید.';await withTimeout(recaptchaVerifier.render(),15000,'نمایش reCAPTCHA زمان‌بر شد. اینترنت یا دسترسی به Google reCAPTCHA را بررسی کنید.');confirmationResult=await withTimeout(auth.signInWithPhoneNumber('+98'+phone.slice(1),recaptchaVerifier),20000,'Firebase در مهلت مقرر پاسخ ارسال SMS را نداد.');$('otpWrap').style.display='block';button.textContent='تأیید کد و ورود';$('modalText').textContent='کد تأیید برای شما پیامک شد.';button.onclick=verifySms}catch(e){const code=e?.code||'';let msg='ارسال پیامک انجام نشد.';if(code==='auth/unauthorized-domain')msg='دامنه سایت در Firebase مجاز نشده است. در Authentication > Settings، دامنه dehghanzademahdi-netizen.github.io را اضافه کنید.';else if(code==='auth/operation-not-allowed')msg='ورود با شماره موبایل در Firebase فعال نشده است. Phone را در Authentication > Sign-in method فعال کنید.';else if(code==='auth/quota-exceeded'||code==='auth/billing-not-enabled')msg='ارسال SMS فعال نیست یا پروژه Firebase به Cloud Billing متصل نیست. Firebase برای SMS احراز هویت تلفنی به Billing نیاز دارد.';else if(code==='auth/too-many-requests')msg='تعداد درخواست SMS زیاد شده است. کمی بعد دوباره امتحان کنید یا از شماره دیگری برای تست استفاده کنید.';else if(code==='auth/invalid-phone-number')msg='شماره موبایل معتبر نیست.';else if(code==='auth/captcha-check-failed')msg='تأیید امنیتی reCAPTCHA ناموفق بود. دوباره تلاش کنید.';else if(code==='auth/timeout')msg=e?.message||'ارسال پیامک زمان‌بر شد؛ وضعیت اتصال و reCAPTCHA را بررسی کنید.';else if(code==='auth/invalid-api-key')msg='کلید Firebase برای سایت معتبر نیست. تنظیمات Web App در Firebase باید اصلاح شود.';else if(e?.message)msg+=` ${e.message}`;$('modalText').textContent=msg;try{recaptchaVerifier?.clear()}catch(_){}recaptchaVerifier=null;button.onclick=startSmsLogin}finally{button.disabled=false}}
async function verifySms(){const code=($('otp')?.value||'').trim();if(!/^\d{6}$/.test(code)){$('modalText').textContent='کد ۶ رقمی را وارد کنید.';return}const button=$('modalAction');button.disabled=true;$('modalText').textContent='در حال تأیید...';try{if(!confirmationResult)throw new Error('کد جدید دریافت کنید.');const result=await confirmationResult.confirm(code),u=result.user;sessionStorage.setItem('chemlinkLoggedIn','1');sessionStorage.setItem('chemlinkPhone',u.phoneNumber||'');sessionStorage.setItem('chemlinkUid',u.uid||'');hideLogin();location.reload()}catch(e){$('modalText').textContent=`کد واردشده صحیح نیست یا منقضی شده است.${e?.code?` (${e.code})`:''}`}finally{button.disabled=false}}
function getRoot(){return fetch(DB_URL+'/chemlink.json').then(r=>{if(!r.ok)throw Error('database');return r.json()}).then(x=>x||{})}
async function loadListings(){if(!loggedIn()){renderLocked();return}try{const root=await getRoot(),arr=Array.isArray(root.offers)?root.offers:Object.values(root.offers||{});listings=arr.filter(x=>x&&String(x.status||'').toUpperCase()==='APPROVED').map(x=>({name:x.name||'',official:x.publishedOfficial||x.official||'',market:x.publishedMarket||x.market||'',place:x.place||'',time:x.time||'',photo:x.photo||''}));renderListings(listings)}catch(e){const g=$('listingGrid');if(g)g.innerHTML='<div class="empty">اتصال به بازار آنلاین برقرار نشد.</div>}}
function renderLocked(){$('listingGrid').innerHTML='<div class="empty"><b>برای دیدن آگهی‌ها وارد حساب شوید</b><br><button class="primary" id="lockedLogin">ورود با پیامک</button></div>';const b=$('lockedLogin');if(b)b.onclick=showLogin}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m))}
function renderListings(items){$('listingGrid').innerHTML=items.length?items.map(x=>`<article class="listing-card">${x.photo?`<img src="${x.photo}" alt="">`:''}<div class="listing-body"><h3>${esc(x.name)}</h3><p>${esc(x.official)}</p><p>${esc(x.market)}</p><small>${esc(x.place)} ${x.time?'• '+esc(x.time):''}</small><button class="primary full details">مشاهده جزئیات و خرید</button></div></article>`).join(''):'<div class="empty">در حال حاضر آگهی تأییدشده‌ای وجود ندارد.</div>';document.querySelectorAll('.details').forEach(b=>b.onclick=()=>alert('برای هماهنگی خرید با مدیریت ChemLink تماس بگیرید.'))}
function wire(){['loginBtn','searchBtn','postBtn','ctaPost','footerLogin','footerPost'].forEach(id=>{const el=$(id);if(el)el.onclick=e=>{e.preventDefault();showLogin()}});$('closeModal')?.addEventListener('click',hideLogin);$('modal')?.addEventListener('click',e=>{if(e.target===$('modal'))hideLogin()});const button=$('modalAction');if(button)button.onclick=startSmsLogin;document.querySelectorAll('.category,.filter').forEach(el=>el.addEventListener('click',e=>{if(!loggedIn()){e.preventDefault();showLogin()}}));document.querySelectorAll('.app-top-btn.ios').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showIOSInstall()}));$('searchInput')?.addEventListener('input',()=>{const q=$('searchInput').value.trim().toLowerCase();renderListings(listings.filter(x=>(x.name+' '+x.official+' '+x.market+' '+x.place).toLowerCase().includes(q))});if(loggedIn()&&$('searchInput'))$('searchInput').disabled=false;loadListings()}
window.addEventListener('error',e=>{const t=$('modalText');if(t)t.textContent=`خطای صفحه: ${e.message||'خطای ناشناخته'}`});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
