const DB_URL='https://chemlink-8909b-default-rtdb.firebaseio.com';
const PROJECT_ID='chemlink-8909b';
const API_KEY='AIzaSyDeiURyc0INZpvA00hmRnEqwtGW3h63pgE';
let confirmationResult=null,recaptchaVerifier=null,listings=[];
const $=id=>document.getElementById(id);
const loggedIn=()=>sessionStorage.getItem('chemlinkLoggedIn')==='1';
function showLogin(){const m=$('modal');if(!m)return;m.classList.add('show','open');m.setAttribute('aria-hidden','false');setTimeout(()=>$('phone')?.focus(),50)}
function hideLogin(){const m=$('modal');if(!m)return;m.classList.remove('show','open');m.setAttribute('aria-hidden','true')}
function normalizePhone(v){v=(v||'').replace(/\s|-/g,'');return v.startsWith('+98')?'0'+v.slice(3):v}
function validPhone(v){return /^09\d{9}$/.test(v)}
async function loadFirebase(){if(!window.firebase)throw new Error('Firebase SDK بارگذاری نشده است.');if(!firebase.apps.length)firebase.initializeApp({apiKey:API_KEY,authDomain:`${PROJECT_ID}.firebaseapp.com`,projectId:PROJECT_ID});if(!firebase.auth)throw new Error('Firebase Authentication SDK بارگذاری نشده است.');return firebase.auth()}
async function startSmsLogin(){const phone=normalizePhone($('phone')?.value);if(!validPhone(phone)){$('modalText').textContent='شماره موبایل معتبر ۱۱ رقمی وارد کنید.';return}const button=$('modalAction');button.disabled=true;$('modalText').textContent='در حال آماده‌سازی ارسال کد...';try{const auth=await loadFirebase();if(recaptchaVerifier){try{recaptchaVerifier.clear()}catch(_){}recaptchaVerifier=null}recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha-container',{size:'normal'});await recaptchaVerifier.render();$('modalText').textContent='تأیید امنیتی را انجام دهید.';confirmationResult=await auth.signInWithPhoneNumber('+98'+phone.slice(1),recaptchaVerifier);$('otpWrap').style.display='block';button.textContent='تأیید کد و ورود';$('modalText').textContent='کد تأیید برای شما پیامک شد.';button.onclick=verifySms}catch(e){const code=e?.code?` (${e.code})`:'';const msg=e?.message?` ${e.message}`:'';$('modalText').textContent=`ارسال پیامک انجام نشد${code}.${msg}`;try{recaptchaVerifier?.clear()}catch(_){}recaptchaVerifier=null;button.onclick=startSmsLogin}finally{button.disabled=false}}
async function verifySms(){const code=($('otp')?.value||'').trim();if(!/^\d{6}$/.test(code)){$('modalText').textContent='کد ۶ رقمی را وارد کنید.';return}const button=$('modalAction');button.disabled=true;$('modalText').textContent='در حال تأیید...';try{if(!confirmationResult)throw new Error('کد جدید دریافت کنید.');const result=await confirmationResult.confirm(code),u=result.user;sessionStorage.setItem('chemlinkLoggedIn','1');sessionStorage.setItem('chemlinkPhone',u.phoneNumber||'');sessionStorage.setItem('chemlinkUid',u.uid||'');hideLogin();location.reload()}catch(e){$('modalText').textContent=`کد واردشده صحیح نیست یا منقضی شده است.${e?.code?` (${e.code})`:''}`}finally{button.disabled=false}}
function getRoot(){return fetch(DB_URL+'/chemlink.json').then(r=>{if(!r.ok)throw Error('database');return r.json()}).then(x=>x||{})}
async function loadListings(){if(!loggedIn()){renderLocked();return}try{const root=await getRoot(),arr=Array.isArray(root.offers)?root.offers:Object.values(root.offers||{});listings=arr.filter(x=>x&&String(x.status||'').toUpperCase()==='APPROVED').map(x=>({name:x.name||'',official:x.publishedOfficial||x.official||'',market:x.publishedMarket||x.market||'',place:x.place||'',time:x.time||'',photo:x.photo||''}));renderListings(listings)}catch(e){const g=$('listingGrid');if(g)g.innerHTML='<div class="empty">اتصال به بازار آنلاین برقرار نشد.</div>'}}
function renderLocked(){$('listingGrid').innerHTML='<div class="empty"><b>برای دیدن آگهی‌ها وارد حساب شوید</b><br><button class="primary" id="lockedLogin">ورود با پیامک</button></div>';const b=$('lockedLogin');if(b)b.onclick=showLogin}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m))}
function renderListings(items){$('listingGrid').innerHTML=items.length?items.map(x=>`<article class="listing-card">${x.photo?`<img src="${x.photo}" alt="">`:''}<div class="listing-body"><h3>${esc(x.name)}</h3><p>${esc(x.official)}</p><p>${esc(x.market)}</p><small>${esc(x.place)} ${x.time?'• '+esc(x.time):''}</small><button class="primary full details">مشاهده جزئیات و خرید</button></div></article>`).join(''):'<div class="empty">در حال حاضر آگهی تأییدشده‌ای وجود ندارد.</div>';document.querySelectorAll('.details').forEach(b=>b.onclick=()=>alert('برای هماهنگی خرید با مدیریت ChemLink تماس بگیرید.'))}
function wire(){['loginBtn','searchBtn','postBtn','ctaPost','footerLogin','footerPost'].forEach(id=>{const el=$(id);if(el)el.onclick=e=>{e.preventDefault();showLogin()}});$('closeModal')?.addEventListener('click',hideLogin);$('modal')?.addEventListener('click',e=>{if(e.target===$('modal'))hideLogin()});const button=$('modalAction');if(button)button.onclick=startSmsLogin;document.querySelectorAll('.category,.filter').forEach(el=>el.addEventListener('click',e=>{if(!loggedIn()){e.preventDefault();showLogin()}}));$('searchInput')?.addEventListener('input',()=>{const q=$('searchInput').value.trim().toLowerCase();renderListings(listings.filter(x=>(x.name+' '+x.official+' '+x.market+' '+x.place).toLowerCase().includes(q)))});if(loggedIn()&&$('searchInput'))$('searchInput').disabled=false;loadListings()}
window.addEventListener('error',e=>{const t=$('modalText');if(t)t.textContent=`خطای صفحه: ${e.message||'خطای ناشناخته'}`});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();