const DB_URL='https://chemlink-8909b-default-rtdb.firebaseio.com';
const PROJECT_ID='chemlink-8909b';
const API_KEY='AIzaSyDeiURyc0INZpvA00hmRnEqwtGW3h63pgE';
let confirmationResult=null,recaptchaVerifier=null,listings=[];
const $=id=>document.getElementById(id);
const loggedIn=()=>sessionStorage.getItem('chemlinkLoggedIn')==='1';
function showLogin(){const m=$('modal');if(!m)return;m.classList.add('show','open');m.style.display='flex';m.setAttribute('aria-hidden','false');setTimeout(()=>$('phone')?.focus(),50)}
function hideLogin(){const m=$('modal');if(!m)return;m.classList.remove('show','open');m.style.display='none';m.setAttribute('aria-hidden','true')}
function showIOSInstall(){const s=$('app-download');if(!s)return;let g=$('iosInstallGuide');if(!g){g=document.createElement('div');g.id='iosInstallGuide';g.style.cssText='margin-top:18px;padding:18px 20px;border:1px solid #dbe3ee;border-radius:16px;background:#f8fafc;color:#10233e;line-height:1.9';g.innerHTML='<strong style="display:block;font-size:15px;margin-bottom:7px">📱 نصب ChemLink روی آیفون</strong><span style="display:block;font-size:12px;color:#475569">این دکمه نمی‌تواند به‌تنهایی برنامه را به صفحه اصلی آیفون اضافه کند؛ iOS این کار را از داخل Safari انجام می‌دهد.</span><ol style="margin:9px 0 0;padding-right:22px;font-size:12px;color:#334155"><li>همین سایت را با <b>Safari</b> باز کنید.</li><li>دکمه <b>Share / اشتراک‌گذاری</b> را بزنید.</li><li><b>Add to Home Screen / افزودن به صفحه اصلی</b> را انتخاب کنید.</li><li>اگر گزینه <b>Open as Web App / باز کردن به‌عنوان وب‌اپ</b> نمایش داده شد، آن را روشن کنید و <b>Add</b> را بزنید.</li></ol><div style="margin-top:10px;font-size:10px;color:#64748b">بعد از این کار آیکون ChemLink روی Home Screen آیفون اضافه می‌شود.</div>';s.querySelector('.app-download-inner')?.appendChild(g)}g.scrollIntoView({behavior:'smooth',block:'center'});g.style.boxShadow='0 0 0 3px rgba(14,165,233,.15)';setTimeout(()=>g.style.boxShadow='',1800)}
function normalizePhone(v){v=(v||'').replace(/\s|-/g,'');return v.startsWith('+98')?'0'+v.slice(3):v}
function validPhone(v){return /^09\d{9}$/.test(v)}
async function loadFirebase(){if(!window.firebase)throw new Error('Firebase SDK بارگذاری نشده است.');if(!firebase.apps.length)firebase.initializeApp({apiKey:API_KEY,authDomain:`${PROJECT_ID}.firebaseapp.com`,projectId:PROJECT_ID});if(!firebase.auth)throw new Error('Firebase Authentication SDK بارگذاری نشده است.');return firebase.auth()}
function withTimeout(p,ms,label){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(Object.assign(new Error(label),{code:'auth/timeout'})),ms))])}
async function startSmsLogin(){const phone=normalizePhone($('phone')?.value);if(!validPhone(phone)){$('modalText').textContent='شماره موبایل معتبر ۱۱ رقمی وارد کنید.';return}const button=$('modalAction');button.disabled=true;$('modalText').textContent='در حال ارسال کد تأیید...';try{const auth=await withTimeout(loadFirebase(),10000,'Firebase پاسخ نداد.');if(!firebase.functions)throw new Error('Firebase Functions SDK بارگذاری نشده است.');const functions=firebase.app().functions('us-central1');const sendOtp=functions.httpsCallable('sendSmsOtp');await withTimeout(sendOtp({phone,purpose:'user'}),20000,'سامانه پیامکی پاسخ نداد.');$('otpWrap').style.display='block';button.textContent='تأیید کد و ورود';$('modalText').textContent='کد تأیید برای شما پیامک شد.';button.onclick=verifySms}catch(e){const code=e?.code||'';let msg='ارسال پیامک انجام نشد.';if(code==='functions/resource-exhausted')msg=e?.message||'لطفاً کمی بعد دوباره درخواست کنید.';else if(code==='functions/invalid-argument')msg=e?.message||'اطلاعات واردشده معتبر نیست.';else if(code==='functions/unavailable')msg='ارتباط با سامانه پیامکی برقرار نشد. دوباره تلاش کنید.';else if(code==='functions/not-found')msg=e?.message||'سرویس پیامکی هنوز منتشر نشده است.';else if(e?.message)msg=e.message;$('modalText').textContent=msg;button.onclick=startSmsLogin}finally{button.disabled=false}}
async function verifySms(){const code=($('otp')?.value||'').trim();const phone=normalizePhone($('phone')?.value);if(!validPhone(phone)){$('modalText').textContent='شماره موبایل معتبر نیست.';return}if(!/^\d{6}$/.test(code)){$('modalText').textContent='کد ۶ رقمی را وارد کنید.';return}const button=$('modalAction');button.disabled=true;$('modalText').textContent='در حال تأیید...';try{const functions=firebase.app().functions('us-central1');const verifyOtp=functions.httpsCallable('verifySmsOtp');const result=await withTimeout(verifyOtp({phone,code,purpose:'user'}),20000,'تأیید کد زمان‌بر شد.');const data=result.data;if(!data?.customToken)throw new Error('توکن ورود دریافت نشد.');const auth=await loadFirebase();const user=await auth.signInWithCustomToken(data.customToken);sessionStorage.setItem('chemlinkLoggedIn','1');sessionStorage.setItem('chemlinkPhone',data.phone||user.user?.phoneNumber||'');sessionStorage.setItem('chemlinkUid',data.uid||user.user?.uid||'');hideLogin();location.reload()}catch(e){const codeName=e?.code||'';let msg='کد واردشده صحیح نیست یا منقضی شده است.';if(codeName==='functions/deadline-exceeded')msg='کد تأیید منقضی شده است. دوباره کد بگیرید.';else if(codeName==='functions/not-found')msg='کد تأیید پیدا نشد. دوباره درخواست کد کنید.';else if(codeName==='functions/resource-exhausted')msg=e?.message||'تعداد تلاش‌ها بیش از حد مجاز است.';else if(e?.message)msg=e.message;$('modalText').textContent=msg}finally{button.disabled=false}}
function getRoot(){return fetch(DB_URL+'/chemlink.json').then(r=>{if(!r.ok)throw Error('database');return r.json()}).then(x=>x||{})}
async function loadListings(){if(!loggedIn()){renderLocked();return}try{const root=await getRoot(),arr=Array.isArray(root.offers)?root.offers:Object.values(root.offers||{});listings=arr.filter(x=>x&&String(x.status||'').toUpperCase()==='APPROVED').map(x=>({name:x.name||'',official:x.publishedOfficial||x.official||'',market:x.publishedMarket||x.market||'',place:x.place||'',time:x.time||'',photo:x.photo||''}));renderListings(listings)}catch(e){const g=$('listingGrid');if(g)g.innerHTML='<div class="empty">اتصال به بازار آنلاین برقرار نشد.</div>}}
function renderLocked(){$('listingGrid').innerHTML='<div class="empty"><b>برای دیدن آگهی‌ها وارد حساب شوید</b><br><button class="primary" id="lockedLogin">ورود با پیامک</button></div>';const b=$('lockedLogin');if(b)b.onclick=showLogin}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m))}
function renderListings(items){$('listingGrid').innerHTML=items.length?items.map(x=>`<article class="listing-card">${x.photo?`<img src="${x.photo}" alt="">`:''}<div class="listing-body"><h3>${esc(x.name)}</h3><p>${esc(x.official)}</p><p>${esc(x.market)}</p><small>${esc(x.place)} ${x.time?'• '+esc(x.time):''}</small><button class="primary full details">مشاهده جزئیات و خرید</button></div></article>`).join(''):'<div class="empty">در حال حاضر آگهی تأییدشده‌ای وجود ندارد.</div>';document.querySelectorAll('.details').forEach(b=>b.onclick=()=>alert('برای هماهنگی خرید با مدیریت ChemLink تماس بگیرید.'))}
function wire(){['loginBtn','searchBtn','postBtn','ctaPost','footerLogin','footerPost'].forEach(id=>{const el=$(id);if(el)el.onclick=e=>{e.preventDefault();showLogin()}});$('closeModal')?.addEventListener('click',hideLogin);$('modal')?.addEventListener('click',e=>{if(e.target===$('modal'))hideLogin()});const button=$('modalAction');if(button)button.onclick=startSmsLogin;document.querySelectorAll('.category,.filter').forEach(el=>el.addEventListener('click',e=>{if(!loggedIn()){e.preventDefault();showLogin()}}));document.querySelectorAll('.app-top-btn.ios').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showIOSInstall()}));$('searchInput')?.addEventListener('input',()=>{const q=$('searchInput').value.trim().toLowerCase();renderListings(listings.filter(x=>(x.name+' '+x.official+' '+x.market+' '+x.place).toLowerCase().includes(q))});if(loggedIn()&&$('searchInput'))$('searchInput').disabled=false;loadListings()}
window.addEventListener('error',e=>{const t=$('modalText');if(t)t.textContent=`خطای صفحه: ${e.message||'خطای ناشناخته'}`});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
