const DB='https://chemlink-8909b-default-rtdb.firebaseio.com';
let listings=[];let allUsers=[];
const grid=document.getElementById('listingGrid'),input=document.getElementById('searchInput'),modal=document.getElementById('modal');
const fallback=[{name:'مونو اتانول آمین (MEA)',meta:'پتروشیمی شازند · ۲۰۰ کیلوگرمی',price:'تماس برای قیمت',type:'فروش'},{name:'متانول صنعتی',meta:'تحویل از انبار · تهران',price:'تماس برای قیمت',type:'فروش'},{name:'سود کاستیک پرک',meta:'گرید صنعتی · ۲۵ کیلوگرمی',price:'استعلام قیمت',type:'فروش'}];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function normalize(o){return {id:o.id||o.offerId||Date.now(),name:o.name||o.title||o.productName||'ماده شیمیایی',meta:[o.city,o.location,o.grade,o.weight,o.quantity].filter(Boolean).join(' · ')||'اطلاعات محصول',price:o.price||o.amount||'استعلام قیمت',type:o.type||o.mode||o.offerType||'فروش',raw:o}}
function render(items=listings){grid.innerHTML=items.length?items.map(x=>`<article class="listing"><div class="listing-top"><span class="badge">${esc(x.type)}</span><span class="meta">ChemLink</span></div><h3>${esc(x.name)}</h3><div class="meta">${esc(x.meta)}</div><div class="price"><b>${esc(x.price)}</b><span>جزئیات ←</span></div></article>`).join(''):'<div class="listing"><h3>آگهی‌ای پیدا نشد</h3><div class="meta">عبارت دیگری را جستجو کنید.</div></div>'}
async function loadCloud(){try{const r=await fetch(`${DB}/chemlink/offers.json`);if(!r.ok)throw Error();const data=await r.json();const raw=Array.isArray(data)?data:(data?Object.values(data):[]);listings=raw.map(normalize);if(!listings.length)listings=fallback;render()}catch(e){listings=fallback;render()}}
async function loadUsers(){try{const r=await fetch(`${DB}/chemlink/usersByPhone.json`);const d=await r.json();allUsers=d?Object.values(d):[];const suppliers=allUsers.filter(u=>/supplier|تامین|تأمین/i.test(u.type||'')).length;const consumers=allUsers.filter(u=>/consumer|مصرف/i.test(u.type||'')).length;const vals=document.querySelectorAll('.stats-grid strong');if(vals[1]&&suppliers)vals[1].textContent=suppliers+'+';if(vals[2]&&consumers)vals[2].textContent=consumers+'+'}catch(e){}}
function search(){const q=input.value.trim().toLowerCase();render(!q?listings:listings.filter(x=>(x.name+' '+x.meta+' '+x.type).toLowerCase().includes(q)));document.getElementById('listings').scrollIntoView({behavior:'smooth'})}
document.getElementById('searchBtn').onclick=search;input.addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{input.value=b.dataset.q;search()});document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{input.value=b.dataset.cat;search()});
function openModal(title,text){document.getElementById('modalTitle').textContent=title;document.getElementById('modalText').textContent=text;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
document.getElementById('loginBtn').onclick=()=>openModal('ورود به ChemLink','ورود وب با حساب آنلاین ChemLink انجام می‌شود.');document.getElementById('postBtn').onclick=()=>openModal('ثبت آگهی','برای ثبت آگهی باید وارد حساب کاربری شوید.');document.getElementById('ctaPost').onclick=()=>openModal('ثبت آگهی','برای ثبت آگهی باید وارد حساب کاربری شوید.');document.getElementById('footerLogin').onclick=e=>{e.preventDefault();openModal('ورود به ChemLink','ورود وب با حساب آنلاین ChemLink انجام می‌شود.')};document.getElementById('footerPost').onclick=e=>{e.preventDefault();openModal('ثبت آگهی','برای ثبت آگهی باید وارد حساب کاربری شوید.')};document.getElementById('closeModal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};loadCloud();loadUsers();
