const DB='https://chemlink-8909b-default-rtdb.firebaseio.com';
const MANAGER_WA='989357236476';
const FIREBASE_CONFIG={apiKey:'AIzaSyDeiURyc0INZpvA00hmRnEqwtGW3h63pgE',authDomain:'chemlink-8909b.firebaseapp.com',projectId:'chemlink-8909b',storageBucket:'chemlink-8909b.firebasestorage.app',messagingSenderId:'28638491737',appId:'1:28638491737:android:f84ffbc5517de3ab6c6d48'};
let listings=[];let allUsers=[];let activeType='همه';let loggedIn=sessionStorage.getItem('chemlinkLoggedIn')==='1';let confirmationResult=null;let authReady=false;
try{firebase.initializeApp(FIREBASE_CONFIG);firebase.auth().onAuthStateChanged(user=>{authReady=true;loggedIn=!!user;sessionStorage.setItem('chemlinkLoggedIn',loggedIn?'1':'0');updateLoginUi();if(loggedIn){document.getElementById('searchInput').disabled=false;loadCloud();loadUsers();}else{document.getElementById('searchInput').disabled=true;render([]);}});}catch(e){authReady=true;loggedIn=false;sessionStorage.removeItem('chemlinkLoggedIn');}
const grid=document.getElementById('listingGrid'),input=document.getElementById('searchInput'),modal=document.getElementById('modal');
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const clean=s=>String(s??'').trim();
function normalizePhone(v){let p=String(v||'').replace(/[^0-9+]/g,'');if(p.startsWith('0098'))p='+98'+p.slice(4);if(p.startsWith('98')&&!p.startsWith('+98'))p='+'+p;if(p.startsWith('09'))p='+98'+p.slice(1);return p;}
function normalize(o,key=''){const status=clean(o.status).toUpperCase();const type=clean(o.type||o.mode||o.offerType||'فروش');return{id:o.id||o.offerId||key||`${o.phone||o.owner||''}-${o.createdAt||o.name||Date.now()}`,name:o.name||o.title||o.productName||'ماده شیمیایی',official:o.publishedOfficial||o.official||'',market:o.publishedMarket||o.market||'',place:o.place||o.city||o.location||'',time:o.time||o.deliveryTime||'',supplier:o.supplier||'',description:o.description||'',photo:o.photo||'',type,status,raw:o};}
function extractOffers(data){if(Array.isArray(data))return data.map((o,i)=>[String(i),o]);if(data&&typeof data==='object')return Object.entries(data);return[];}
function updateLoginUi(){const b=document.getElementById('loginBtn');if(b)b.textContent=loggedIn?'خروج از حساب':'ورود / ثبت‌نام';}
function render(items=listings){if(!loggedIn){grid.innerHTML='<div class="listing"><h3>برای دیدن آگهی‌ها وارد حساب شوید</h3><div class="meta">برای مشاهده آگهی‌های واقعی ChemLink و ثبت آگهی، ابتدا با شماره موبایل و کد پیامکی وارد شوید.</div><button class="primary" style="margin-top:16px" id="listingLogin">ورود / ثبت‌نام با پیامک</button></div>';document.getElementById('listingLogin')?.addEventListener('click',()=>openModal('ورود با پیامک','شماره موبایل خود را وارد کنید تا کد تأیید پیامکی دریافت کنید.'));return;}grid.innerHTML=items.length?items.map(x=>`<article class="listing"><div class="listing-top"><span class="badge">${esc(x.type)}</span><span class="meta">آگهی تأییدشده ChemLink.ir</span></div>${x.photo?`<img class="listing-photo" src="${esc(x.photo)}" alt="${esc(x.name)}" loading="lazy">`:''}<h3>${esc(x.name)}</h3>${x.official?`<div class="meta">قیمت رسمی: ${esc(x.official)}</div>`:''}${x.market?`<div class="meta">قیمت بازار: ${esc(x.market)}</div>`:''}${x.place?`<div class="meta">مکان تحویل: ${esc(x.place)}</div>`:''}${x.time?`<div class="meta">زمان تحویل: ${esc(x.time)}</div>`:''}${x.description?`<div class="meta listing-desc">${esc(x.description)}</div>`:''}<div class="price"><b>${esc(x.market||x.official||'تماس برای قیمت')}</b><button class="details" data-id="${esc(x.id)}">مشاهده جزئیات و خرید ←</button></div></article>`).join(''):'<div class="listing"><h3>فعلاً آگهی تأییدشده‌ای وجود ندارد</h3><div class="meta">هر آگهی که در اپ ChemLink تأیید و منتشر شود، بعد از ورود در سایت نیز نمایش داده می‌شود.</div></div>';grid.querySelectorAll('.details').forEach(b=>b.onclick=()=>showOffer(b.dataset.id));}
function visible(){const q=input.value.trim().toLowerCase();return listings.filter(x=>(activeType==='همه'||x.type===activeType||((activeType==='فروش'||activeType==='خرید')&&x.type.includes(activeType)))&&(!q||(x.name+' '+x.official+' '+x.market+' '+x.place+' '+x.time+' '+x.description+' '+x.type).toLowerCase().includes(q)));}
function showOffer(id){if(!loggedIn)return openModal('ورود با پیامک','برای مشاهده جزئیات آگهی ابتدا وارد حساب شوید.');const x=listings.find(v=>String(v.id)===String(id));if(!x)return;document.getElementById('modalTitle').textContent=x.name;document.getElementById('modalText').innerHTML=`<div class="offer-detail">${x.official?`<div><b>قیمت رسمی:</b> ${esc(x.official)}</div>`:''}${x.market?`<div><b>قیمت بازار:</b> ${esc(x.market)}</div>`:''}${x.place?`<div><b>مکان تحویل:</b> ${esc(x.place)}</div>`:''}${x.time?`<div><b>زمان تحویل:</b> ${esc(x.time)}</div>`:''}${x.description?`<div><b>توضیحات:</b> ${esc(x.description)}</div>`:''}<p>برای خرید و هماهنگی این آگهی با مدیریت ChemLink در ارتباط باشید.</p></div>`;document.getElementById('phone').style.display='none';document.getElementById('otpWrap').style.display='none';document.getElementById('recaptcha-container').style.display='none';document.getElementById('modalAction').textContent='ارتباط با مدیریت در واتساپ';document.getElementById('modalAction').onclick=()=>window.open(`https://wa.me/${MANAGER_WA}?text=${encodeURIComponent('سلام، درباره آگهی «'+x.name+'» در ChemLink اطلاعات می‌خواهم.')}`,'_blank');modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
async function loadCloud(){try{const r=await fetch(`${DB}/chemlink/offers.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();listings=extractOffers(data).map(([key,o])=>normalize(o||{},key)).filter(x=>x.status==='APPROVED');render(visible());const active=document.querySelector('.stats-grid strong');if(active)active.textContent=loggedIn?listings.length.toLocaleString('fa-IR'):'—';}catch(e){listings=[];render([])}}
async function loadUsers(){try{const r=await fetch(`${DB}/chemlink/usersByPhone.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();allUsers=d?Object.values(d):[];const suppliers=allUsers.filter(u=>/supplier|تامین|تأمین/i.test(u.type||'')).length;const consumers=allUsers.filter(u=>/consumer|مصرف/i.test(u.type||'')).length;const vals=document.querySelectorAll('.stats-grid strong');if(vals[1])vals[1].textContent=loggedIn?suppliers.toLocaleString('fa-IR'):'—';if(vals[2])vals[2].textContent=loggedIn?consumers.toLocaleString('fa-IR'):'—';}catch(e){}}
function search(){if(!loggedIn)return openModal('ورود با پیامک','برای جستجو و مشاهده آگهی‌ها ابتدا وارد حساب شوید.');render(visible());document.getElementById('listings').scrollIntoView({behavior:'smooth'});}
document.getElementById('searchBtn').onclick=search;input.addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{if(!loggedIn)return openModal('ورود با پیامک','برای مشاهده آگهی‌ها ابتدا وارد حساب شوید.');input.value=b.dataset.q;search()});document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{if(!loggedIn)return openModal('ورود با پیامک','برای مشاهده آگهی‌ها ابتدا وارد حساب شوید.');input.value=b.dataset.cat;search()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{if(!loggedIn)return openModal('ورود با پیامک','برای مشاهده آگهی‌ها ابتدا وارد حساب شوید.');document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeType=b.textContent.trim();render(visible())});
function openModal(title,text){document.getElementById('modalTitle').textContent=title;document.getElementById('modalText').textContent=text;document.getElementById('phone').style.display='';document.getElementById('otpWrap').style.display='none';document.getElementById('recaptcha-container').style.display='block';document.getElementById('modalAction').textContent='دریافت کد پیامکی';document.getElementById('modalAction').onclick=()=>startSmsLogin();modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
async function startSmsLogin(){const phone=normalizePhone(document.getElementById('phone').value);if(!/^\+98\d{10}$/.test(phone)){document.getElementById('modalText').textContent='شماره موبایل ایران را به شکل 09xxxxxxxxx وارد کنید.';return;}if(!window.firebase||!firebase.auth){document.getElementById('modalText').textContent='سرویس ورود بارگذاری نشده است. صفحه را دوباره باز کنید.';return;}try{document.getElementById('modalAction').disabled=true;document.getElementById('modalText').textContent='در حال آماده‌سازی ارسال کد پیامکی...';if(window.recaptchaVerifier){try{window.recaptchaVerifier.clear();}catch(e){}}window.recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha-container',{size:'invisible',callback:()=>{}});const verifier=window.recaptchaVerifier;confirmationResult=await firebase.auth().signInWithPhoneNumber(phone,verifier);document.getElementById('otpWrap').style.display='block';document.getElementById('modalText').textContent='کد تأیید پیامکی ارسال شد. کد ۶ رقمی را وارد کنید.';document.getElementById('modalAction').textContent='تأیید و ورود';document.getElementById('modalAction').onclick=confirmSmsLogin;}catch(e){try{window.recaptchaVerifier?.clear();}catch(x){}const msg=e?.code==='auth/operation-not-allowed'?'ورود با شماره موبایل در Firebase فعال نشده است.':e?.code==='auth/invalid-phone-number'?'شماره موبایل معتبر نیست.':e?.code==='auth/too-many-requests'?'تعداد درخواست‌ها زیاد شده؛ کمی بعد دوباره تلاش کنید.':`ارسال کد انجام نشد: ${e?.message||'خطای نامشخص'}`;document.getElementById('modalText').textContent=msg;document.getElementById('modalAction').disabled=false;}}
async function confirmSmsLogin(){const otp=document.getElementById('otp').value.trim();if(!/^\d{6}$/.test(otp)){document.getElementById('modalText').textContent='کد ۶ رقمی را درست وارد کنید.';return;}if(!confirmationResult){document.getElementById('modalText').textContent='ابتدا کد پیامکی را دریافت کنید.';return;}try{document.getElementById('modalAction').disabled=true;const result=await confirmationResult.confirm(otp);const phone=normalizePhone(result.user.phoneNumber);sessionStorage.setItem('chemlinkLoggedIn','1');sessionStorage.setItem('chemlinkPhone',phone);loggedIn=true;document.getElementById('modalText').textContent='ورود با موفقیت انجام شد.';document.getElementById('phone').style.display='none';document.getElementById('otpWrap').style.display='none';document.getElementById('recaptcha-container').style.display='none';document.getElementById('modalAction').textContent='ادامه';document.getElementById('modalAction').disabled=false;document.getElementById('modalAction').onclick=()=>{closeModal();updateLoginUi();document.getElementById('searchInput').disabled=false;loadCloud();loadUsers();};updateLoginUi();loadCloud();loadUsers();}catch(e){document.getElementById('modalText').textContent=e?.code==='auth/invalid-verification-code'?'کد واردشده صحیح نیست.':`ورود انجام نشد: ${e?.message||'خطای نامشخص'}`;document.getElementById('modalAction').disabled=false;}}
function logout(){try{firebase.auth().signOut();}catch(e){}sessionStorage.removeItem('chemlinkLoggedIn');sessionStorage.removeItem('chemlinkPhone');loggedIn=false;updateLoginUi();document.getElementById('searchInput').disabled=true;render([]);}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');try{window.recaptchaVerifier?.clear();}catch(e){}}
document.getElementById('loginBtn').onclick=()=>loggedIn?logout():openModal('ورود با پیامک','شماره موبایل خود را وارد کنید تا کد تأیید پیامکی دریافت کنید.');document.getElementById('postBtn').onclick=()=>loggedIn?openModal('ثبت آگهی','فرم ثبت آگهی سایت در مرحله بعدی فعال می‌شود.'):openModal('ورود برای ثبت آگهی','برای ثبت آگهی ابتدا با شماره موبایل وارد حساب شوید.');document.getElementById('ctaPost').onclick=()=>loggedIn?openModal('ثبت آگهی','فرم ثبت آگهی سایت در مرحله بعدی فعال می‌شود.'):openModal('ورود برای ثبت آگهی','برای ثبت آگهی ابتدا با شماره موبایل وارد حساب شوید.');document.getElementById('footerLogin').onclick=e=>{e.preventDefault();loggedIn?logout():openModal('ورود با پیامک','شماره موبایل خود را وارد کنید تا کد تأیید پیامکی دریافت کنید.')};document.getElementById('footerPost').onclick=e=>{e.preventDefault();loggedIn?openModal('ثبت آگهی','فرم ثبت آگهی سایت در مرحله بعدی فعال می‌شود.'):openModal('ورود برای ثبت آگهی','برای ثبت آگهی ابتدا با شماره موبایل وارد حساب شوید.')};document.getElementById('closeModal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal();};
render([]);if(loggedIn){document.getElementById('searchInput').disabled=false;loadCloud();loadUsers();}setInterval(()=>{if(loggedIn)loadCloud()},15000);setInterval(()=>{if(loggedIn)loadUsers()},30000);
